### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by chanhenry54** [idonotknowwhatiamdoing/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
  - Make sure section titles are in a header format
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Great job!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by idonotknowwhatiamdoing** [comment]
Hi, I accidentally filled in the checkbox for "All titles of sections are formatted as headers or similar" but I undid it just now. Will it be an issue? 
Also, should I mark all the checkboxes I finished fixing before submitting a regrade request?

**Comment by chanhenry54** [comment]
No worries! I'll mark the checkboxes when reviewing the regrade request just so I can keep track of which things need to be re-checked. I just marked them all as complete!
